---
# file: tasks/main.yml
# Install app to init system.
#
#

- name: install libselinux-python binary for Ansible to work
  sudo: True
  yum: name=libselinux-python state=present
  when: ansible_pkg_mgr == "yum"


- name: copy SysV INIT to /etc/init.d
  sudo: True
  template:
    src:   "{{ playbook_dir }}/{{ item.value.src }}"
    dest:  "/etc/init.d/{{ item.value.dest }}"
    owner: root
    group: root
    mode:  0755
  with_dict: init_sysv | default({})


- name: copy Upstart INIT to /etc/init
  sudo: True
  template:
    src:   "{{ playbook_dir }}/{{ item.value.src }}"
    dest:  "/etc/init/{{ item.value.dest }}"
    owner: root
    group: root
    mode:  0644
  with_dict: init_upstart | default({})
  when: not (ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 7)
